using GoAhead.Commands.BlockingShared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GoAhead.Commands.GridStyle
{
    class PrintPartitionPinConstraint : CommandWithFileOutput
    {
        private const string PORT_KIND_BEGIN = "Begin";
        private const string PORT_KIND_END = "End";

        private const string DIRECTION_WEST = "West";
        private const string DIRECTION_EAST = "East";
        private const string DIRECTION_NORTH = "North";
        private const string DIRECTION_SOUTH = "South";

        protected override void DoCommandAction()
        {
            CheckParameters();

            OutputManager.WriteTCLOutput($"set_property HD.PARTPIN_LOCS {GetLocationAndPortName()} [get_pins {GetSignalName()}]; # generated by GoAhead");

            // prevent the specific port from blocking
            if(PreventBlocking)
            {
                ExcludePortsFromBlocking command = new ExcludePortsFromBlocking();
                command.PortName = GetPortName();
                command.Location = SwitchboxName;
                command.CheckForExistence = false;
                command.IncludeAllPorts = true;
                CommandExecuter.Instance.Execute(command);
            }
        }

        private string GetSignalName()
        {
            return $"{InstanceName}/{SignalName}[{SignalIndex.ToString()}]";
        }

        private string GetLocationAndPortName()
        {
            return $"{SwitchboxName}/{GetPortName()}";
        }

        private string GetPortName()
        {
            string portName = string.Empty;

            //// 7-Series port name has following structure: <WWT|EE|SS|NN><LENGTH><BEG|END><INDEX>
            //portName += CardinalDirection[0].ToString() + CardinalDirection[0].ToString();
            //portName += Length.ToString();
            //portName += PortKind.Substring(0, 3).ToUpper();
            //portName += PortIndex.ToString();

            // UltraScale/UltraScale+ port name has following structure: <WW|EE|SS|NN><LENGTH>_<W|E>_<BEG|END><INDEX>, <WW|EE|SS|NN>12_<BEG|END><INDEX>
            portName += CardinalDirection[0].ToString() + CardinalDirection[0].ToString();
            portName += Length.ToString();
            if (12 != Length)
            {
                portName += "_E_";
            }
            else
            {
                portName += "_";
            }
            portName += PortKind.Substring(0, 3).ToUpper();
            portName += PortIndex.ToString();

            return portName;
        }

        private void CheckParameters()
        {
            bool portKindIsCorrect = PortKind.Equals(PORT_KIND_BEGIN) || PortKind.Equals(PORT_KIND_END);
            bool cardinalDirectionIsCorrect = CardinalDirection.Equals(DIRECTION_EAST) ||
                                              CardinalDirection.Equals(DIRECTION_WEST) ||
                                              CardinalDirection.Equals(DIRECTION_SOUTH) ||
                                              CardinalDirection.Equals(DIRECTION_NORTH);

            bool signalIndexIsCorrect = SignalIndex >= 0;
            bool portIndexIsCorrect = PortIndex >= 0 && PortIndex <= 3;
            bool instanceNameIsCorrect = !string.IsNullOrEmpty(InstanceName);
            bool signalNameIsCorrect = !string.IsNullOrEmpty(SignalName);
            bool switchboxNameIsCorrect = !string.IsNullOrEmpty(SwitchboxName);

            if (!portKindIsCorrect || !cardinalDirectionIsCorrect || !signalIndexIsCorrect || !portIndexIsCorrect ||
                !instanceNameIsCorrect || !signalNameIsCorrect || !switchboxNameIsCorrect)
            {
                throw new ArgumentException("Unexpected format in one of the parameters.");
            }

        }

        public override void Undo()
        {
            throw new NotImplementedException();
        }

        [Parameter(Comment = "Unblock the partition pin")]
        public bool PreventBlocking = true;

        [Parameter(Comment = "Either Begin or End")]
        public string PortKind = "Begin";

        [Parameter(Comment = "Cardinal direction: North, South, West, or East")]
        public string CardinalDirection = "West";

        [Parameter(Comment = "Index of the signal")]
        public int SignalIndex = 0;

        [Parameter(Comment = "Index of the port")]
        public int PortIndex = 0;

        [Parameter(Comment = "The length of the wire (in terms of number of switchboxes")]
        public int Length = 2;

        [Parameter(Comment = "Instance name of the component")]
        public string InstanceName = "inst_ConnMacro";

        [Parameter(Comment = "The name of the signal")]
        public string SignalName = "p2s";

        [Parameter(Comment = "The name of the switchbox.")]
        public string SwitchboxName = "INT_R_X41Y9";



    }
}
