using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GoAhead.Commands.GridStyle
{
    class PrintExcludePlacementProperty : CommandWithFileOutput
    {
        protected override void DoCommandAction()
        {
            this.CheckParameters();

            this.OutputManager.WriteTCLOutput($"set_property EXCLUDE_PLACEMENT true [get_pblocks pb_{this.InstanceName}]; # generated by GoAhead");
        }

        private void CheckParameters()
        {
            bool instanceNameIsCorrect = !String.IsNullOrEmpty(this.InstanceName);

            if (!instanceNameIsCorrect)
            {
                throw new ArgumentException("Unexpected format in parameters InstanceName.");
            }
        }

        public override void Undo()
        {
            throw new NotImplementedException();
        }

        [Parameter(Comment = "Instance name of the component")]
        public String InstanceName = "inst_ConnMacro";
    }
}
